services:
  core:
    ports:
      - "3000:3000"
    profiles: ["prod"]
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    profiles: ["dev", "prod"]
    env_file:
      - ./.env
    volumes:
      - mongo:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo: