definitions:
  auth.SignInput:
    properties:
      password:
        minLength: 10
        type: string
      username:
        minLength: 5
        type: string
    required:
    - password
    - username
    type: object
  models.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  models.UserModel:
    properties:
      created_at:
        type: string
      id:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/auth/sign-up:
    post:
      consumes:
      - application/json
      parameters:
      - description: data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth.SignInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UserModel'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      security:
      - BearerAuth: []
      summary: get new  tokens
      tags:
      - Auth
swagger: "2.0"
